name: Swift CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    # Pin the runner to a supported Ubuntu version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: '6.1'
      - run: swift test --enable-test-discovery
