name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
      runs-on: ubuntu-22.04
    runs-on: ubuntu-22.04
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    # Pin the runner to a supported Ubuntu version
    runs-on: ubuntu-22.04

    runs-on: ubuntu-22.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "6.0"
      - run: swift test
          swift-version: "6.1"
      - run: swift test

          swift-version: '6.1'
      - run: swift test --enable-test-discovery
